auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    dir: /wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /etc/loki/index
    cache_location: /etc/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /etc/loki/storage

compactor:
  shared_store: filesystem
  working_directory: /etc/loki/compactor  # ✅ 指定 compactor 可用目錄
  retention_enabled: false  # ✅ 禁用自動刪除

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h

